<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_recent_tweets"
 *
 * Auto generated by Extension Builder 2017-01-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '[NITSAN] Twitter plugin to display all your Tweets',
	'description' => '[NITSAN] Twitter extension brings all your recent tweets to your TYPO3 site!',
	'category' => 'plugin',
	'author' => 'Sanjay Chuahan [NITSAN Technologies]',
	'author_email' => 'sanjay@nitsan.in',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
